### PR TITLE
Dijkstra's Algorithm for single source shortest paths using STL

### PR DESCRIPTION
**Pull request by amitbansal7**

### CODE REVIEW

**Comment by Aniket965** [comment]
hi ,its look like you are still working on it let me know when this pr is finished

**Comment by amitbansal7** [comment]
Now it is finished there was a problem with comments because of tabs and spaces.

**Comment by Aniket965** [comment]
i Will recommend using vs code or atom with beautify package you only have to press a command and it will automatically format code for you :)

**Comment by Aniket965** [comment]
nice job :)

**Comment by amitbansal7** [comment]
Thanks for the recommendation :)

**Pull request merged**
